package com.ardeveloper.plut.data.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "Kota".
*/
public class KotaDao extends AbstractDao<Kota, Void> {

    public static final String TABLENAME = "Kota";

    /**
     * Properties of entity Kota.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, int.class, "id", false, "ID");
        public final static Property Nama = new Property(1, String.class, "nama", false, "NAMA");
        public final static Property Kode = new Property(2, String.class, "kode", false, "KODE");
    }


    public KotaDao(DaoConfig config) {
        super(config);
    }
    
    public KotaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"Kota\" (" + //
                "\"ID\" INTEGER NOT NULL ," + // 0: id
                "\"NAMA\" TEXT," + // 1: nama
                "\"KODE\" TEXT);"); // 2: kode
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"Kota\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Kota entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String nama = entity.getNama();
        if (nama != null) {
            stmt.bindString(2, nama);
        }
 
        String kode = entity.getKode();
        if (kode != null) {
            stmt.bindString(3, kode);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Kota entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String nama = entity.getNama();
        if (nama != null) {
            stmt.bindString(2, nama);
        }
 
        String kode = entity.getKode();
        if (kode != null) {
            stmt.bindString(3, kode);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public Kota readEntity(Cursor cursor, int offset) {
        Kota entity = new Kota( //
            cursor.getInt(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // nama
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // kode
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Kota entity, int offset) {
        entity.setId(cursor.getInt(offset + 0));
        entity.setNama(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setKode(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(Kota entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(Kota entity) {
        return null;
    }

    @Override
    public boolean hasKey(Kota entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
